name: CD

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    outputs:
      release-version: ${{ steps.generate_release_version.outputs.release_version }}
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
    - name: Generate release tag
      id: generate_release_tag
      uses: alexvingg/next-release-tag@v1.0.4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag_prefix: 'v'
    - name: Remove leading 'v' from version
      id: generate_release_version
      run: |
        release_tag=${{ steps.generate_release_tag.outputs.release_tag }}
        echo "release_version=${release_tag#v}" >> $GITHUB_OUTPUT
  release:
    needs: prepare-release
    uses: reallifedeveloper/github-workflows/.github/actions/maven-release@main
    with:
      release-version: ${{ needs.prepare-release.outputs.release-version }}
    secrets: inherit
    permissions:
      contents: write
