name: CD

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
    - name: Generate release tag
      id: generate_release_tag
      uses: alexvingg/next-release-tag@v1.0.4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag_prefix: ''
    - name: Create release
      uses: reallifedeveloper/github-workflows/.github/actions/release@main
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        release-version: ${{ steps.generate_release_tag.outputs.release_tag }}
